{
 "title": "QuMine Ingress",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"qumine-ingress\", container=\"qumine-ingress\", pod=~\"qumine-ingress.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"qumine-ingress\", container=\"qumine-ingress\", pod=~\"qumine-ingress.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Registered Routes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(qumine_ingress_routes)", "legendFormat": "routes" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qumine_ingress_connections)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(qumine_ingress_connections) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qumine_ingress_bytes_total[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(qumine_ingress_bytes_total[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qumine_ingress_errors_total[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(qumine_ingress_errors_total[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}